<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.7.0.0',
  'acceptable_sugar_versions' =>
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' =>
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'raw',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => false,
  'name' => 'Layout administration',
  'published_date' => '2016-11-01 17:43:07',
  'type' => 'module',
  'version' => time(),
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'copy' =>
	array (
	0 =>
    array (
      'from' => '<basepath>/custom/Extension/modules/Administration/Ext/Language/en_us.DefaultSetting.php',
      'to' => 'custom/Extension/modules/Administration/Ext/Language/en_us.DefaultSetting.php',
    ),
  1 =>
    array (
      'from' => '<basepath>/custom/Extension/modules/Administration/Ext/Administration/DefaultSetting.php',
      'to' => 'custom/Extension/modules/Administration/Ext/Administration/DefaultSetting.php',
    ),
  2 =>
    array (
      'from' => '<basepath>/custom/modules/Administration/controller.php',
      'to' => 'custom/modules/Administration/controller.php',
    ),
  3 =>
    array (
      'from' => '<basepath>/custom/modules/Administration/tpls/defaultsetting.tpl',
      'to' => 'custom/modules/Administration/tpls/defaultsetting.tpl',
    ),
  4 =>
    array (
      'from' => '<basepath>/custom/modules/Administration/tpls/wrapper.tpl',
      'to' => 'custom/modules/Administration/tpls/wrapper.tpl',
    ),
  5 =>
    array (
      'from' => '<basepath>/custom/modules/Administration/views/view.defaultsetting.php',
      'to' => 'custom/modules/Administration/views/view.defaultsetting.php',
    ),
  ),
);

